"""Add backpopulates to books & author fields

Revision ID: 043ade5ec0a1
Revises: d1f80598864a
Create Date: 2024-10-04 18:12:55.681659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043ade5ec0a1'
down_revision: Union[str, None] = 'd1f80598864a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
